### ISSUE TITLE
add setAccounts to \TYPO3\Party\Domain\Model\AbstractParty

### ISSUE THREAD

**Issue by kaystrobach** [neos/party#13]
Jira issue originally created by user kaystrobach:

adding the following function to \TYPO3\Party\Domain\Model\AbstractParty gives the ability to change the account from the surrounding party, otherwise we always need to have to do the role selection explicitly in the account

```
/****
 * Sets the accounts of this party
 *
 * @param \Doctrine\Common\Collections\Collection $accounts All assigned TYPO3\Flow\Security\Account objects
 * @return void
 */
public function setAccounts($accounts) {
    $this->accounts = $accounts;
}
```

Jira-URL: https://jira.neos.io/browse/FLOW-281

**Comment by kaystrobach** [comment]
As requested this was moved from https://github.com/neos/flow-development-collection/issues/567#issuecomment-254064306

**Comment by markusguenther** [comment]
As this issue is pretty old we can maybe close it.
If this is still relevant feel free to reopen that ❤️
